language: node_js
node_js:
- 12
deploy:
  provider: heroku
  api_key:
    secure: ij9Tk1gUW4qvsmwKzmVbXnRoAjIS3D1G1Q18l7n7kv9GFkB9PkPA3qcnznYR+9xRf4yFCG12hyoBjEOlqHD0/NRUQC3gtvx0l+Oz5mvFTmBMQIC4f/rXx/gc2G8EesKeoHtssCwy0g5xbABiL8M8v+dv3bBEeBofhznUQlD4gGUIdvC54Ho/X/T3re6AIJ6evCekVygNSEZZNC/coYaIIt5UyadVF3noHskEQ99/J6e9/o8q4rKtRJBwTl1fNJLicCAqKksX1At2Xi6MA8KdxO3OUFXUcZ+ifvmP+6PqOnOWOGXIFOx1lLxCttNriAhrtTbRbvfo5hyUPWUbO6q+9j7hGRnvR6OZ6HfuEuU4pyj44zpPgBYaRsENgCoRaTB0XJH1oV9KxRmRC4e8M0K9qUZrZmLtLLQdQDfb9d1GSqMDt4G666ovFuEPOHv11dITCXTQBr454l3TXPKOWh7mGdh9ESRz0ZJylPYLO6RcXUfVgqCg54lS9IQxicfo1QhRfSYBeHLywL3R5B7dkEcG95jcmqId/3wsQkLx2kIpIf6qc5+WGmkRd7RMqsnqEyWh3RRialwMqfoxb99qBQv9KFb3kR4+R4TfXdyIMPIrduWZJLa7iYlYPC2CBlGMszHv+b7SNZ3MKA90nMnBo/Iny5NnY3pVT3wQweMORpMboH0=
  app: WoroAPI
